name: Vintage And Modern Cars
favicon: null
layout_spectrum: 0.7191091901622713
typography_spectrum: 0.5687638644594699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#618aa7'
    - '#57809d'
    - '#507a99'
    - '#030303'
    - '#487392'
  brandStrength: 0.8703845562413335
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
